# fly.toml app configuration file generated for aged-feather-1809 on 2023-08-27T22:33:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-feather-1809"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
